import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
from pathlib import Path

st.set_page_config(
    page_title="Skin Classification System",
    page_icon="🩺",
    layout="centered"
)

st.title("🩺 AI Skin Classification System")

st.write(
    "Upload a skin image to classify it as Healthy or Unhealthy."
)

st.info(
    "⚠️ This system is for educational/research purposes only. "
    "It does not provide a medical diagnosis."
)

# Model path
MODEL_PATH = (
    Path(__file__).resolve().parent.parent
    / "models"
    / "skin_binary_mobilenetv2.keras"
)


@st.cache_resource
def load_model():
    return tf.keras.models.load_model(MODEL_PATH)


try:
    model = load_model()
    st.success("✅ Model loaded successfully!")

except Exception as e:
    st.error("❌ Error loading the model.")
    st.exception(e)
    st.stop()


uploaded_file = st.file_uploader(
    "📷 Upload a skin image",
    type=["jpg", "jpeg", "png"]
)


if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    st.subheader("Uploaded Image")

    st.image(
        image,
        caption="Uploaded Skin Image",
        use_container_width=True
    )

    # Resize image
    img = image.resize((224, 224))

    # Convert image to NumPy array
    img_array = np.array(img).astype("float32")

    # Add batch dimension
    img_array = np.expand_dims(img_array, axis=0)

    # Make prediction
    with st.spinner("🔍 Analyzing image..."):

        prediction = model.predict(
            img_array,
            verbose=0
        )[0][0]

    st.subheader("Prediction Result")

    if prediction >= 0.5:

        result = "UNHEALTHY / ABNORMAL SKIN"
        confidence = prediction * 100

        st.error(f"🔴 {result}")

    else:

        result = "HEALTHY / NORMAL SKIN"
        confidence = (1 - prediction) * 100

        st.success(f"🟢 {result}")

    st.write(f"**Confidence: {confidence:.2f}%**")

    with st.expander("View Model Score"):

        st.write(
            f"Raw prediction score: `{prediction:.6f}`"
        )

        st.write("Score closer to 0 → Healthy")
        st.write("Score closer to 1 → Unhealthy")

    st.warning(
        "⚠️ This prediction is generated by an AI model "
        "and should not be considered a medical diagnosis. "
        "For medical concerns, consult a qualified healthcare professional."
    )